//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Ajax.Utilities {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal JScript() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsAjaxMinJavaScript.Javascript.JScript", typeof(JScript).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ambiguous catch identifier. Cross-browser behavior difference. .
        /// </summary>
        public static string AmbiguousCatchVar {
            get {
                return ResourceManager.GetString("AmbiguousCatchVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ambiguous reference to named function expression. Cross-browser behavior difference.
        /// </summary>
        public static string AmbiguousNamedFunctionExpression {
            get {
                return ResourceManager.GetString("AmbiguousNamedFunctionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Application failed. Please report this issue..
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument defined but not referenced.
        /// </summary>
        public static string ArgumentNotReferenced {
            get {
                return ResourceManager.GetString("ArgumentNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Trailing comma in array literal; cross-browser difference.
        /// </summary>
        public static string ArrayLiteralTrailingComma {
            get {
                return ResourceManager.GetString("ArrayLiteralTrailingComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Arrow functions cannot be constructors.
        /// </summary>
        public static string ArrowCannotBeConstructor {
            get {
                return ResourceManager.GetString("ArrowCannotBeConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Assignment to constant.
        /// </summary>
        public static string AssignmentToConstant {
            get {
                return ResourceManager.GetString("AssignmentToConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid binding syntax.
        /// </summary>
        public static string BadBindingSyntax {
            get {
                return ResourceManager.GetString("BadBindingSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t have &apos;break&apos; outside of loop.
        /// </summary>
        public static string BadBreak {
            get {
                return ResourceManager.GetString("BadBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t have &apos;continue&apos; outside of loop.
        /// </summary>
        public static string BadContinue {
            get {
                return ResourceManager.GetString("BadContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid hexadecimal escape sequence.
        /// </summary>
        public static string BadHexEscapeSequence {
            get {
                return ResourceManager.GetString("BadHexEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Label redefined.
        /// </summary>
        public static string BadLabel {
            get {
                return ResourceManager.GetString("BadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid numeric literal.
        /// </summary>
        public static string BadNumericLiteral {
            get {
                return ResourceManager.GetString("BadNumericLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;return&apos; statement outside of function.
        /// </summary>
        public static string BadReturn {
            get {
                return ResourceManager.GetString("BadReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Missing &apos;case&apos; or &apos;default&apos; statement.
        /// </summary>
        public static string BadSwitch {
            get {
                return ResourceManager.GetString("BadSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Binding pattern requires initializer.
        /// </summary>
        public static string BindingPatternRequiresInitializer {
            get {
                return ResourceManager.GetString("BindingPatternRequiresInitializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unmatched &apos;@else&apos;; no &apos;@if&apos; defined.
        /// </summary>
        public static string CCInvalidElse {
            get {
                return ResourceManager.GetString("CCInvalidElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unmatched &apos;@elif&apos;; no &apos;@if&apos; defined.
        /// </summary>
        public static string CCInvalidElseIf {
            get {
                return ResourceManager.GetString("CCInvalidElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unmatched &apos;@end&apos;; no &apos;@if&apos; defined.
        /// </summary>
        public static string CCInvalidEnd {
            get {
                return ResourceManager.GetString("CCInvalidEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Conditional compilation is turned off.
        /// </summary>
        public static string CCOff {
            get {
                return ResourceManager.GetString("CCOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected class element.
        /// </summary>
        public static string ClassElementExpected {
            get {
                return ResourceManager.GetString("ClassElementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Conditional compilation expression not supported. Comment ignored.
        /// </summary>
        public static string ConditionalCompilationTooComplex {
            get {
                return ResourceManager.GetString("ConditionalCompilationTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;default&apos; can only appear once in a &apos;switch&apos; statement.
        /// </summary>
        public static string DupDefault {
            get {
                return ResourceManager.GetString("DupDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Variable or function declaration redefines the catch error name.
        /// </summary>
        public static string DuplicateCatch {
            get {
                return ResourceManager.GetString("DuplicateCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate class element name.
        /// </summary>
        public static string DuplicateClassElementName {
            get {
                return ResourceManager.GetString("DuplicateClassElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Constant declaration already declared.
        /// </summary>
        public static string DuplicateConstantDeclaration {
            get {
                return ResourceManager.GetString("DuplicateConstantDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate lexical declaration; cannot redefine let or const variables.
        /// </summary>
        public static string DuplicateLexicalDeclaration {
            get {
                return ResourceManager.GetString("DuplicateLexicalDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate module declaration.
        /// </summary>
        public static string DuplicateModuleDeclaration {
            get {
                return ResourceManager.GetString("DuplicateModuleDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name is already defined.
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expecting more source characters.
        /// </summary>
        public static string ErrorEndOfFile {
            get {
                return ResourceManager.GetString("ErrorEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Export statements must be at top level of module.
        /// </summary>
        public static string ExportNotAtModuleLevel {
            get {
                return ResourceManager.GetString("ExportNotAtModuleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected expression.
        /// </summary>
        public static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Function expression expected.
        /// </summary>
        public static string FunctionExpressionExpected {
            get {
                return ResourceManager.GetString("FunctionExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Function name should be a simple identifier; possible browser-specific implementation.
        /// </summary>
        public static string FunctionNameMustBeIdentifier {
            get {
                return ResourceManager.GetString("FunctionNameMustBeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Function defined but not referenced.
        /// </summary>
        public static string FunctionNotReferenced {
            get {
                return ResourceManager.GetString("FunctionNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to High-surrogate pair value not followed by low-surrogate value.
        /// </summary>
        public static string HighSurrogate {
            get {
                return ResourceManager.GetString("HighSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Illegal assignment.
        /// </summary>
        public static string IllegalAssignment {
            get {
                return ResourceManager.GetString("IllegalAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid character.
        /// </summary>
        public static string IllegalChar {
            get {
                return ResourceManager.GetString("IllegalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Implicit property name must be identifier.
        /// </summary>
        public static string ImplicitPropertyNameMustBeIdentifier {
            get {
                return ResourceManager.GetString("ImplicitPropertyNameMustBeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Import statement must include module name.
        /// </summary>
        public static string ImportNoModuleName {
            get {
                return ResourceManager.GetString("ImportNoModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unmatched &apos;else&apos;; no &apos;if&apos; defined.
        /// </summary>
        public static string InvalidElse {
            get {
                return ResourceManager.GetString("InvalidElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to JSParser Exception.
        /// </summary>
        public static string JSParserException {
            get {
                return ResourceManager.GetString("JSParserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reserved words and should not be used as an identifier; cross-browser differences.
        /// </summary>
        public static string KeywordUsedAsIdentifier {
            get {
                return ResourceManager.GetString("KeywordUsedAsIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Low-surrogate pair value not following a high-surrogate value.
        /// </summary>
        public static string LowSurrogate {
            get {
                return ResourceManager.GetString("LowSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Methods not allowed in object literal bindings.
        /// </summary>
        public static string MethodsNotAllowedInBindings {
            get {
                return ResourceManager.GetString("MethodsNotAllowedInBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Function declaration should not be inside a statement. Cross-browser behavior difference.
        /// </summary>
        public static string MisplacedFunctionDeclaration {
            get {
                return ResourceManager.GetString("MisplacedFunctionDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Multiple default exports.
        /// </summary>
        public static string MultipleDefaultExports {
            get {
                return ResourceManager.GetString("MultipleDefaultExports", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New line not allowed.
        /// </summary>
        public static string NewLineNotAllowed {
            get {
                return ResourceManager.GetString("NewLineNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected binding syntax.
        /// </summary>
        public static string NoBinding {
            get {
                return ResourceManager.GetString("NoBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;catch&apos;.
        /// </summary>
        public static string NoCatch {
            get {
                return ResourceManager.GetString("NoCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;@end&apos;.
        /// </summary>
        public static string NoCCEnd {
            get {
                return ResourceManager.GetString("NoCCEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;:&apos;.
        /// </summary>
        public static string NoColon {
            get {
                return ResourceManager.GetString("NoColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;,&apos;.
        /// </summary>
        public static string NoComma {
            get {
                return ResourceManager.GetString("NoComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unterminated comment.
        /// </summary>
        public static string NoCommentEnd {
            get {
                return ResourceManager.GetString("NoCommentEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Imported module has no default export.
        /// </summary>
        public static string NoDefaultModuleExport {
            get {
                return ResourceManager.GetString("NoDefaultModuleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected ///#ENDDEBUG directive.
        /// </summary>
        public static string NoEndDebugDirective {
            get {
                return ResourceManager.GetString("NoEndDebugDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected ///#ENDIF directive.
        /// </summary>
        public static string NoEndIfDirective {
            get {
                return ResourceManager.GetString("NoEndIfDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;=&apos;.
        /// </summary>
        public static string NoEqual {
            get {
                return ResourceManager.GetString("NoEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &quot;from&quot;.
        /// </summary>
        public static string NoExpectedFrom {
            get {
                return ResourceManager.GetString("NoExpectedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;for&apos; or &apos;if&apos; keyword.
        /// </summary>
        public static string NoForOrIf {
            get {
                return ResourceManager.GetString("NoForOrIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected identifier.
        /// </summary>
        public static string NoIdentifier {
            get {
                return ResourceManager.GetString("NoIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Label not found.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;{&apos;.
        /// </summary>
        public static string NoLeftCurly {
            get {
                return ResourceManager.GetString("NoLeftCurly", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;(&apos;.
        /// </summary>
        public static string NoLeftParenthesis {
            get {
                return ResourceManager.GetString("NoLeftParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected identifier or string.
        /// </summary>
        public static string NoMemberIdentifier {
            get {
                return ResourceManager.GetString("NoMemberIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Imported module does not export name.
        /// </summary>
        public static string NoModuleExport {
            get {
                return ResourceManager.GetString("NoModuleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;]&apos;.
        /// </summary>
        public static string NoRightBracket {
            get {
                return ResourceManager.GetString("NoRightBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;,&apos; or &apos;]&apos;.
        /// </summary>
        public static string NoRightBracketOrComma {
            get {
                return ResourceManager.GetString("NoRightBracketOrComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;}&apos;.
        /// </summary>
        public static string NoRightCurly {
            get {
                return ResourceManager.GetString("NoRightCurly", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;)&apos;.
        /// </summary>
        public static string NoRightParenthesis {
            get {
                return ResourceManager.GetString("NoRightParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;,&apos; or &apos;)&apos;.
        /// </summary>
        public static string NoRightParenthesisOrComma {
            get {
                return ResourceManager.GetString("NoRightParenthesisOrComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;;&apos;.
        /// </summary>
        public static string NoSemicolon {
            get {
                return ResourceManager.GetString("NoSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No source set on parser.
        /// </summary>
        public static string NoSource {
            get {
                return ResourceManager.GetString("NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected specifier set.
        /// </summary>
        public static string NoSpecifierSet {
            get {
                return ResourceManager.GetString("NoSpecifierSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected string literal.
        /// </summary>
        public static string NoStringLiteral {
            get {
                return ResourceManager.GetString("NoStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected &apos;while&apos;.
        /// </summary>
        public static string NoWhile {
            get {
                return ResourceManager.GetString("NoWhile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Consider replacing maximum numeric literal with Number.MAX_VALUE.
        /// </summary>
        public static string NumericMaximum {
            get {
                return ResourceManager.GetString("NumericMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Consider replacing minimum numeric literal with Number.MIN_VALUE.
        /// </summary>
        public static string NumericMinimum {
            get {
                return ResourceManager.GetString("NumericMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Numeric literal evaluates to Number.POSITIVE_INFINITY or Number.NEGATIVE_INFINITY.
        /// </summary>
        public static string NumericOverflow {
            get {
                return ResourceManager.GetString("NumericOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Object constructor should take no arguments.
        /// </summary>
        public static string ObjectConstructorTakesNoArguments {
            get {
                return ResourceManager.GetString("ObjectConstructorTakesNoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reserved word used as object literal property name; cross-browser issue..
        /// </summary>
        public static string ObjectLiteralKeyword {
            get {
                return ResourceManager.GetString("ObjectLiteralKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Octal literals are deprecated. Possible cross-browser behavior difference.
        /// </summary>
        public static string OctalLiteralsDeprecated {
            get {
                return ResourceManager.GetString("OctalLiteralsDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A variable argument list must be the last argument.
        /// </summary>
        public static string ParameterListNotLast {
            get {
                return ResourceManager.GetString("ParameterListNotLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Syntax error in regular expression.
        /// </summary>
        public static string RegExpSyntax {
            get {
                return ResourceManager.GetString("RegExpSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resource reference must be single constant argument.
        /// </summary>
        public static string ResourceReferenceMustBeConstant {
            get {
                return ResourceManager.GetString("ResourceReferenceMustBeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rest parameter can only be in last position.
        /// </summary>
        public static string RestParameterNotLast {
            get {
                return ResourceManager.GetString("RestParameterNotLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Semicolon insertion rules applied.
        /// </summary>
        public static string SemicolonInsertion {
            get {
                return ResourceManager.GetString("SemicolonInsertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Setter methods must have a single formal argument.
        /// </summary>
        public static string SetterMustHaveOneParameter {
            get {
                return ResourceManager.GetString("SetterMustHaveOneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Class constructor must be normal method.
        /// </summary>
        public static string SpecialConstructor {
            get {
                return ResourceManager.GetString("SpecialConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Always use full statement blocks.
        /// </summary>
        public static string StatementBlockExpected {
            get {
                return ResourceManager.GetString("StatementBlockExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Class static method cannot be named &quot;prototype&quot;.
        /// </summary>
        public static string StaticPrototype {
            get {
                return ResourceManager.GetString("StaticPrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict operator always evaluates to true or false.
        /// </summary>
        public static string StrictComparisonIsAlwaysTrueOrFalse {
            get {
                return ResourceManager.GetString("StrictComparisonIsAlwaysTrueOrFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow certain argument names.
        /// </summary>
        public static string StrictModeArgumentName {
            get {
                return ResourceManager.GetString("StrictModeArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow certain catch binding names.
        /// </summary>
        public static string StrictModeCatchName {
            get {
                return ResourceManager.GetString("StrictModeCatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow duplicate argument names.
        /// </summary>
        public static string StrictModeDuplicateArgument {
            get {
                return ResourceManager.GetString("StrictModeDuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow duplicate property names.
        /// </summary>
        public static string StrictModeDuplicateProperty {
            get {
                return ResourceManager.GetString("StrictModeDuplicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow certain function names.
        /// </summary>
        public static string StrictModeFunctionName {
            get {
                return ResourceManager.GetString("StrictModeFunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow assignment to certain variables.
        /// </summary>
        public static string StrictModeInvalidAssign {
            get {
                return ResourceManager.GetString("StrictModeInvalidAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow certain delete operands.
        /// </summary>
        public static string StrictModeInvalidDelete {
            get {
                return ResourceManager.GetString("StrictModeInvalidDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow ++ or -- on certain objects.
        /// </summary>
        public static string StrictModeInvalidPreOrPost {
            get {
                return ResourceManager.GetString("StrictModeInvalidPreOrPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow with-statements.
        /// </summary>
        public static string StrictModeNoWith {
            get {
                return ResourceManager.GetString("StrictModeNoWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow assignment to undefined variables.
        /// </summary>
        public static string StrictModeUndefinedVariable {
            get {
                return ResourceManager.GetString("StrictModeUndefinedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strict-mode does not allow certain variable names.
        /// </summary>
        public static string StrictModeVariableName {
            get {
                return ResourceManager.GetString("StrictModeVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to String literal is not safe for inline.
        /// </summary>
        public static string StringNotInlineSafe {
            get {
                return ResourceManager.GetString("StringNotInlineSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Suspect assignment operator.
        /// </summary>
        public static string SuspectAssignment {
            get {
                return ResourceManager.GetString("SuspectAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Suspect equality comparison.
        /// </summary>
        public static string SuspectEquality {
            get {
                return ResourceManager.GetString("SuspectEquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Suspect semicolon.
        /// </summary>
        public static string SuspectSemicolon {
            get {
                return ResourceManager.GetString("SuspectSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Syntax error.
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Too many errors. The file might not be a JavaScript file.
        /// </summary>
        public static string TooManyTokensSkipped {
            get {
                return ResourceManager.GetString("TooManyTokensSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to convert from binding to reference.
        /// </summary>
        public static string UnableToConvertFromBinding {
            get {
                return ResourceManager.GetString("UnableToConvertFromBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to convert from reference to binding.
        /// </summary>
        public static string UnableToConvertToBinding {
            get {
                return ResourceManager.GetString("UnableToConvertToBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to End of file encountered before function is properly closed.
        /// </summary>
        public static string UnclosedFunction {
            get {
                return ResourceManager.GetString("UnclosedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Function has not been defined.
        /// </summary>
        public static string UndeclaredFunction {
            get {
                return ResourceManager.GetString("UndeclaredFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Variable has not been declared.
        /// </summary>
        public static string UndeclaredVariable {
            get {
                return ResourceManager.GetString("UndeclaredVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected &apos;;&apos;.
        /// </summary>
        public static string UnexpectedSemicolon {
            get {
                return ResourceManager.GetString("UnexpectedSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unterminated ASP.NET block.
        /// </summary>
        public static string UnterminatedAspNetBlock {
            get {
                return ResourceManager.GetString("UnterminatedAspNetBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unterminated string constant.
        /// </summary>
        public static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Statement label never referenced.
        /// </summary>
        public static string UnusedLabel {
            get {
                return ResourceManager.GetString("UnusedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Variable defined but not referenced.
        /// </summary>
        public static string VariableDefinedNotReferenced {
            get {
                return ResourceManager.GetString("VariableDefinedNotReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;with&apos; statement not recommended.
        /// </summary>
        public static string WithNotRecommended {
            get {
                return ResourceManager.GetString("WithNotRecommended", resourceCulture);
            }
        }
    }
}
